// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using erikCorp.ITDevelop.Data.ORM;

namespace erikCorp.ITDevelop.Data.Migrations
{
    [DbContext(typeof(ITDevelopDataContext))]
    [Migration("20200202192010_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("erikCorp.ITDevelop.Domain.Entities.Mural", b =>
                {
                    b.Property<int>("muralId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data");

                    b.Property<string>("autor");

                    b.Property<string>("aviso");

                    b.Property<string>("email");

                    b.Property<string>("titulo");

                    b.HasKey("muralId");

                    b.ToTable("Mural");
                });
#pragma warning restore 612, 618
        }
    }
}
